os:
  - linux
  - osx

language: node_js

node_js:
  - 4.0
  - 4
  - 5
  - 6.0
  - 6

install: npm install

after_script:
  - npm install coveralls -g
  - cat ./coverage/lcov.info | coveralls && rm -rf ./coverage
